name: Terraform Deployment
on: push
jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Install Terraform
        id: terraform-install
        run: wget -O terraform.zip https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip && unzip terraform.zip && chmod +x terraform && sudo mv terraform /usr/local/bin
      - name: Check Terraform Version
        id: terraform-version
        run: terraform --version
      - name: Switch Directory
        id: swtich-directory 
        run: cd GCP-Projects
      - name: Init Terraform
        id: terraform-init
        run: terraform init
      - name: Plan Terraform
        id: plan-terraform
        run: terraform plan